version: "3"

services:
  server:
    image: microblogpub/microblogpub:latest 
    container_name: microblogpub
    user: 1001:1001
    restart: always
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
      - ./app/scss:/app/app/scss
    ports:
      - "8082:8000"
